import React, { useState } from "react";
import { HelpCircle, MessageSquare, Mail, FileText, ChevronDown, AlertTriangle } from "lucide-react";
import { ActiveTab } from "./Header";
import { LegalDocument, LegalPolicyModal } from "./LegalPolicyModal";
import { authFetch } from "./auth/authStorage";

interface HelpDeskViewProps { setActiveTab: (tab: ActiveTab) => void; onRaiseGrievance?: () => void; }
const FAQS = [
 ["What can IP-SAKTI Sahayak help me with?", "It provides AI-assisted research and decision support for AYUSH, intellectual property, traditional knowledge, biodiversity and regulatory topics using indexed knowledge sources."],
 ["When should I request expert guidance?", "If an answer has low confidence or you need human review, choose the expert category shown below the answer. The request is routed to a matching registered expert when one is available."],
 ["What happens after I contact an expert?", "The selected expert is informed about the query. The request, assigned expert and status are available under My Workspace → Expert Guidance."],
 ["Can I raise a grievance about an answer?", "Yes. Use Raise a Grievance to submit a concern about an AI response, source, technical issue or general query."],
 ["Are the answers legal advice?", "No. The platform provides AI-assisted information and decision support. Important legal, regulatory and filing decisions should be verified against current authoritative sources and qualified professionals."],
];
export const HelpDeskView: React.FC<HelpDeskViewProps> = ({ onRaiseGrievance }) => {
 const [openFaq,setOpenFaq]=useState<number|null>(null); const [legalDocument,setLegalDocument]=useState<LegalDocument|null>(null); const [contactSending,setContactSending]=useState(false); const [contactSent,setContactSent]=useState(false); const [contactError,setContactError]=useState<string|null>(null);
 const submitContact=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setContactSending(true);setContactSent(false);setContactError(null);const form=e.currentTarget;const d=new FormData(form);try{const r=await authFetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:d.get('name'),email:d.get('email'),subject:d.get('subject'),message:d.get('message')})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.detail||'We could not send your message. Please try again.');setContactSent(true);form.reset();}catch(err){setContactError(err instanceof Error?err.message:'We could not send your message.');}finally{setContactSending(false);}};
 return <div className="w-full bg-slate-50 min-h-[calc(100vh-4rem)] border-x-2 border-slate-200"><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-8 space-y-5">
  <div className="bg-white border-2 border-slate-300 rounded-2xl p-5 sm:p-7 shadow-sm"><div className="flex items-start gap-3"><div className="w-10 h-10 rounded-xl bg-emerald-50 border border-emerald-200 flex items-center justify-center shrink-0"><HelpCircle className="w-5 h-5 text-emerald-700"/></div><div><p className="text-[10px] uppercase tracking-wider font-bold text-emerald-700">Support Centre</p><h1 className="text-2xl font-serif font-bold text-slate-900 mt-1">HelpDesk</h1><p className="text-sm text-slate-600 mt-1">Find answers, contact the support team, raise a grievance, or review platform policies.</p></div></div></div>
  <div className="grid md:grid-cols-2 gap-4"><button type="button" onClick={()=>onRaiseGrievance?.()} className="text-left bg-white border-2 border-slate-300 hover:border-emerald-500 rounded-2xl p-5 shadow-sm"><AlertTriangle className="w-5 h-5 text-amber-600"/><h2 className="text-sm font-bold text-slate-900 mt-3">Raise a Grievance</h2><p className="text-xs text-slate-500 mt-1">Report an incorrect response, source concern, technical issue or other problem.</p></button><button type="button" onClick={()=>document.getElementById('helpdesk-faqs')?.scrollIntoView({behavior:'smooth',block:'start'})} className="text-left bg-white border-2 border-slate-300 hover:border-emerald-500 rounded-2xl p-5 shadow-sm"><HelpCircle className="w-5 h-5 text-emerald-700"/><h2 className="text-sm font-bold text-slate-900 mt-3">FAQs</h2><p className="text-xs text-slate-500 mt-1">Quick answers about Sahayak, expert guidance and support.</p></button></div>
  <section id="helpdesk-faqs" className="bg-white border-2 border-slate-300 rounded-2xl overflow-hidden shadow-sm"><div className="px-5 py-4 border-b-2 border-slate-200"><h2 className="text-base font-bold text-slate-900">Frequently Asked Questions</h2></div>{FAQS.map(([q,a],i)=><div key={q} className="border-b border-slate-200 last:border-b-0"><button type="button" onClick={()=>setOpenFaq(openFaq===i?null:i)} className="w-full px-5 py-4 flex items-center justify-between gap-4 text-left hover:bg-slate-50"><span className="text-sm font-semibold text-slate-800">{q}</span><ChevronDown className={`w-4 h-4 text-slate-500 transition-transform ${openFaq===i?'rotate-180':''}`}/></button>{openFaq===i&&<div className="px-5 pb-4 text-xs leading-relaxed text-slate-600">{a}</div>}</div>)}</section>
  <section className="bg-slate-950 border-2 border-slate-800 rounded-2xl p-5 sm:p-6 text-white shadow-sm"><div className="flex items-center gap-2"><Mail className="w-5 h-5 text-emerald-300"/><h2 className="text-base font-bold">Contact Us</h2></div><p className="text-xs text-slate-300 mt-1">Send a support message to the IP-SAKTI Sahayak team.</p><form onSubmit={submitContact} className="mt-5 grid sm:grid-cols-2 gap-3"><input name="name" required placeholder="Name" className="rounded-xl border border-slate-700 bg-slate-900 px-3 py-2.5 text-sm text-white placeholder:text-slate-400 outline-none focus:border-emerald-400"/><input name="email" type="email" required placeholder="Email" className="rounded-xl border border-slate-700 bg-slate-900 px-3 py-2.5 text-sm text-white placeholder:text-slate-400 outline-none focus:border-emerald-400"/><input name="subject" required placeholder="Subject" className="sm:col-span-2 rounded-xl border border-slate-700 bg-slate-900 px-3 py-2.5 text-sm text-white placeholder:text-slate-400 outline-none focus:border-emerald-400"/><textarea name="message" required rows={5} placeholder="How can we help?" className="sm:col-span-2 rounded-xl border border-slate-700 bg-slate-900 px-3 py-2.5 text-sm text-white placeholder:text-slate-400 outline-none focus:border-emerald-400 resize-y"/>{contactError&&<div className="sm:col-span-2 rounded-xl border border-rose-400/40 bg-rose-950/40 px-3 py-2 text-xs text-rose-200">{contactError}</div>}{contactSent&&<div className="sm:col-span-2 rounded-xl border border-emerald-400/40 bg-emerald-950/40 px-3 py-2 text-xs text-emerald-200">Your message has been received. A confirmation email has been sent.</div>}<div className="sm:col-span-2 flex justify-end"><button disabled={contactSending} className="inline-flex items-center gap-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs px-5 py-2.5 disabled:opacity-60"><MessageSquare className="w-4 h-4"/>{contactSending?'Sending...':'Send Message'}</button></div></form></section>
  <section className="bg-white border-2 border-slate-300 rounded-2xl p-5 shadow-sm"><div className="flex items-center gap-2"><FileText className="w-5 h-5 text-slate-700"/><h2 className="text-base font-bold text-slate-900">Policies & Information</h2></div><div className="grid sm:grid-cols-2 gap-3 mt-4"><button type="button" onClick={()=>setLegalDocument('terms')} className="rounded-xl border-2 border-slate-200 hover:border-emerald-400 p-4 text-left"><p className="text-sm font-semibold text-slate-900">Terms & Conditions</p><p className="text-xs text-slate-500 mt-1">How the service may be used and important limitations.</p></button><button type="button" onClick={()=>setLegalDocument('privacy')} className="rounded-xl border-2 border-slate-200 hover:border-emerald-400 p-4 text-left"><p className="text-sm font-semibold text-slate-900">Privacy Policy</p><p className="text-xs text-slate-500 mt-1">What information the platform processes and how it is handled.</p></button></div></section>
 </div><LegalPolicyModal document={legalDocument} onClose={()=>setLegalDocument(null)}/></div>;
};
