import { jsPDF } from 'jspdf';

// ---------------------------------------------------------------------------
// Frontend-only PDF export. Builds a clean, paginated PDF report directly
// from data already present in the UI (no backend endpoint, no screenshot —
// text is drawn natively so it stays crisp and selectable).
// ---------------------------------------------------------------------------

export interface PDFKeyValue {
  label: string;
  value: string;
}

export interface PDFSection {
  heading?: string;
  /** Plain paragraphs, rendered with wrapping. */
  paragraphs?: string[];
  /** label/value pairs, rendered as "Label: value" lines. */
  keyValues?: PDFKeyValue[];
  /** Bulleted or numbered list items. */
  list?: string[];
  listStyle?: 'bullet' | 'number';
}

export interface PDFReportOptions {
  title: string;
  subtitle?: string;
  sections: PDFSection[];
  fileName: string;
}

const MARGIN = 18; // mm
const PAGE_WIDTH = 210; // A4 mm
const PAGE_HEIGHT = 297; // A4 mm
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

export function generatePDFReport(options: PDFReportOptions): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = MARGIN;

  const ensureSpace = (needed: number) => {
    if (y + needed > PAGE_HEIGHT - MARGIN) {
      addFooter(doc);
      doc.addPage();
      y = MARGIN;
    }
  };

  const writeLines = (lines: string[], lineHeight: number) => {
    for (const line of lines) {
      ensureSpace(lineHeight);
      doc.text(line, MARGIN, y);
      y += lineHeight;
    }
  };

  // --- Document header ---
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42); // slate-900
  const titleLines = doc.splitTextToSize(options.title, CONTENT_WIDTH);
  writeLines(titleLines, 7);

  if (options.subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(71, 85, 105); // slate-600
    const subtitleLines = doc.splitTextToSize(options.subtitle, CONTENT_WIDTH);
    writeLines(subtitleLines, 5.5);
  }

  y += 2;
  doc.setDrawColor(203, 213, 225); // slate-300
  ensureSpace(4);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 8;

  // --- Sections ---
  for (const section of options.sections) {
    if (section.heading) {
      ensureSpace(10);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12.5);
      doc.setTextColor(6, 78, 59); // emerald-900
      doc.text(section.heading, MARGIN, y);
      y += 6.5;
    }

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59); // slate-800

    if (section.paragraphs) {
      for (const para of section.paragraphs) {
        if (!para) continue;
        const lines = doc.splitTextToSize(para, CONTENT_WIDTH);
        writeLines(lines, 5);
        y += 2;
      }
    }

    if (section.keyValues) {
      for (const kv of section.keyValues) {
        if (!kv.value) continue;
        const combined = `${kv.label}: ${kv.value}`;
        const lines = doc.splitTextToSize(combined, CONTENT_WIDTH);
        // Bold the label portion by drawing label separately when it fits on one line
        writeLines(lines, 5);
      }
      y += 2;
    }

    if (section.list && section.list.length > 0) {
      section.list.forEach((item, idx) => {
        const marker = section.listStyle === 'number' ? `${idx + 1}.` : '\u2022';
        const indent = 6;
        const lines = doc.splitTextToSize(item, CONTENT_WIDTH - indent);
        lines.forEach((line: string, lineIdx: number) => {
          ensureSpace(5);
          if (lineIdx === 0) {
            doc.text(marker, MARGIN, y);
          }
          doc.text(line, MARGIN + indent, y);
          y += 5;
        });
      });
      y += 2;
    }

    y += 4; // spacing between sections
  }

  addFooter(doc);

  // Add page numbers across all pages now that total count is known
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 10, { align: 'right' });
  }

  doc.save(options.fileName);
}

function addFooter(doc: jsPDF) {
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text(
    'Generated by IP-SAKTI Sahayak — AI-assisted decision support, not formal legal counsel.',
    MARGIN,
    PAGE_HEIGHT - 10
  );
}
