"""
Confidence scoring — combines the top fused retrieval score, number of
supporting chunks, and citation-validation results into a single
High/Moderate/Low/Insufficient-evidence verdict with explicit reasons, so the
frontend can render it directly (`ConfidenceMetric` in types.ts).
"""
from __future__ import annotations

from app.config import settings
from app.safety.citation_validator import ValidationResult
from app.schemas import ConfidenceLevel, ConfidenceMetric


def compute_confidence(
    top_score: float,
    chunk_count: int,
    validation: ValidationResult,
) -> ConfidenceMetric:
    # Penalize hallucinated citation tags and unverified-authority citations.
    penalty = 0.10 * validation.hallucinated_tag_count + 0.05 * validation.unverified_authority_count
    adjusted_score = max(0.0, top_score - penalty)

    reasons: list[str] = []
    level: ConfidenceLevel

    if adjusted_score > settings.confidence_high_threshold and chunk_count >= settings.min_chunks_for_high_confidence:
        level = "High"
        reasons.append(f"Multi-source convergence across {chunk_count} relevant indexed provisions.")
        reasons.append("Direct statutory/regulatory citations matched the query terms closely.")
    elif adjusted_score > settings.confidence_moderate_threshold and chunk_count >= 2:
        level = "Moderate"
        reasons.append("Relevant regulatory principles retrieved with partial textual alignment.")
        reasons.append("Sufficient basis for analytical decision-support; verify specifics before filing.")
    elif adjusted_score > settings.confidence_low_threshold:
        level = "Low"
        reasons.append("Limited direct textual overlap with indexed statutory provisions.")
        reasons.append("Recommend consulting official gazettes or a specialist before relying on this.")
    else:
        level = "Insufficient evidence"
        reasons.append("No directly matching legislative provisions or official guidelines were found in the indexed knowledge base.")

    if validation.hallucinated_tag_count:
        reasons.append(
            f"{validation.hallucinated_tag_count} citation marker(s) generated by the model did not "
            "match any retrieved source and were removed."
        )
    if validation.unverified_authority_count:
        reasons.append(
            f"{validation.unverified_authority_count} retrieved source(s) are outside the recognised "
            "authority allow-list and should be independently verified."
        )

    return ConfidenceMetric(level=level, score=round(min(1.0, max(0.05, adjusted_score)), 3), reasons=reasons)
